import 'dotenv/config';
import crypto from 'node:crypto';
import http from 'node:http';
import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import cron from 'node-cron';
import { Server } from 'socket.io';
import { createAdapter } from '@socket.io/redis-adapter';
import { createClient } from 'redis';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import { rankCandidates, scoreCompatibility } from './matching.js';
import { authenticateDevelopmentAccount, createId, store } from './store.js';
import { apiLimiter, globalErrorHandler } from './security.js';
import { httpLogger, requestId } from './observability.js';
import { secureAuthRouter } from './auth.js';
import { maskContactInfo } from './services/contact-guard.js';
import { recordOutcomeLabel as saveOutcomeLabel } from './services/feedback-labeling.js';

const app = express(); const server = http.createServer(app); const PORT = Number(process.env.PORT || 4000); const JWT_SECRET = process.env.JWT_SECRET || 'development-only-change-before-production'; const PEPPER = process.env.VERIFICATION_PEPPER || 'development-only-pepper';
globalThis.__checkmateStore = store;
const io = new Server(server, { cors: { origin: process.env.CLIENT_ORIGIN || 'http://localhost:5173' } });
let redisClient = null;
if (process.env.REDIS_URL) {
  let publisher;
  let subscriber;
  try {
    publisher = createClient({ url: process.env.REDIS_URL, socket: { connectTimeout: 1000, reconnectStrategy: false } });
    subscriber = publisher.duplicate();
    // Prevent a transient Redis outage from terminating the web API process.
    publisher.on('error', () => undefined);
    subscriber.on('error', () => undefined);
    await Promise.all([publisher.connect(), subscriber.connect()]);
    io.adapter(createAdapter(publisher, subscriber));
    redisClient = publisher;
    console.log('Redis adapter and TTL message store enabled');
  } catch {
    // A failed connect can leave a Redis client in the closed state. Calling
    // destroy() on that state throws ClientClosedError and prevents the API
    // from falling back to the in-memory chat store.
    for (const client of [publisher, subscriber]) {
      try {
        if (client?.isOpen) client.destroy();
      } catch {
        // Redis is optional in local Mock mode; cleanup errors are non-fatal.
      }
    }
    console.warn('Redis is unavailable; using in-memory chat fallback. Start Redis to enable shared real-time delivery.');
  }
}
app.use(helmet()); app.use(requestId); app.use(httpLogger); app.use(cors({ origin: process.env.CLIENT_ORIGIN || 'http://localhost:5173', credentials: true })); app.use(cookieParser()); app.use(express.json({ limit: '32kb' })); app.use('/api/v1', apiLimiter); app.use('/api/v1/auth/secure', secureAuthRouter());
const digest = (value) => crypto.createHmac('sha256', PEPPER).update(value).digest('hex');
const tokenFor = (user) => jwt.sign({ sub: user.id, role: user.role, operatorId: user.operatorId, jti: createId() }, JWT_SECRET, { issuer: 'checkmate', expiresIn: '30m' });
function requireToken(req, res, next) { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'UNAUTHORIZED' }); try { req.auth = jwt.verify(token, JWT_SECRET, { issuer: 'checkmate' }); return next(); } catch { return res.status(401).json({ error: 'TOKEN_INVALID_OR_EXPIRED' }); } }
function requireOperator(req, res, next) { if (req.auth.role !== 'operator') return res.status(403).json({ error: 'OPERATOR_ROLE_REQUIRED' }); return next(); }

const allowedConflictCategories = new Set(['noise', 'cleaning', 'guests', 'shared_space', 'sleep_schedule', 'communication', 'other']);
const allowedRoomTypes = new Set(['private_room', 'shared_room', 'multi_room']);
const allowedShareCounts = new Set([2, 3, 4]);
const allowedGenderPreferences = new Set(['any', 'female', 'male', 'non_binary']);
const allowedAgeBands = new Set(['any', '20s', '30s', '40_plus']);
const boundedInt = (value, min, max, fallback = 0) => {
  if (value === null || value === undefined || value === '') return fallback;
  const numeric = Number(value);
  return Number.isInteger(numeric) ? Math.min(max, Math.max(min, numeric)) : fallback;
};
const normalizeConflictCategories = (categories) => Array.isArray(categories) ? [...new Set(categories.filter((category) => allowedConflictCategories.has(category)))].slice(0, 5) : [];
const getChatFeaturesForMatch = (matchId, tenantId) => store.chatMetrics.get(`${matchId}:${tenantId}`) || {};
const normalizeMatchingPreferences = (body = {}) => ({ roomType: allowedRoomTypes.has(body.roomType) ? body.roomType : 'private_room', shareCount: allowedShareCounts.has(Number(body.shareCount)) ? Number(body.shareCount) : 2, preferredGender: allowedGenderPreferences.has(body.preferredGender) ? body.preferredGender : 'any', ageBand: allowedAgeBands.has(body.ageBand) ? body.ageBand : 'any' });
const matchesAgeBand = (age, ageBand) => ageBand === 'any' || (ageBand === '20s' && age >= 20 && age < 30) || (ageBand === '30s' && age >= 30 && age < 40) || (ageBand === '40_plus' && age >= 40);
const matchesPreference = (user, preferences) => (preferences.preferredGender === 'any' || user.gender === preferences.preferredGender) && matchesAgeBand(Number(user.age), preferences.ageBand);

const recordOutcomeLabel = (input) => saveOutcomeLabel({
  ...input,
  store,
  createId,
  getChatFeatures: getChatFeaturesForMatch,
});

app.get('/health', (_req, res) => res.json({ ok: true, product: 'CheckMate', mode: redisClient ? 'redis' : 'memory' }));
app.post('/api/v1/auth/login', (req, res) => { const user = authenticateDevelopmentAccount(req.body.accountId, req.body.password); if (!user) return res.status(401).json({ error: 'INVALID_CREDENTIALS' }); res.json({ accessToken: tokenFor(user), tokenType: 'Bearer', expiresInSeconds: 1800, user: { id: user.id, accountId: user.accountId, pseudonym: user.pseudonym, role: user.role, operatorId: user.operatorId } }); });

// Embedded B2B attribution: retained by operator and room, never by raw personal identifiers.
app.post('/api/v1/funnel/events', (req, res) => { const { operatorId, roomId, funnelId, step } = req.body; if (!operatorId || !roomId || !funnelId || !step) return res.status(400).json({ error: 'ATTRIBUTION_FIELDS_REQUIRED' }); const event = { id: createId(), operatorId, roomId, funnelId, step, createdAt: new Date().toISOString() }; store.funnelEvents.push(event); res.status(201).json({ event }); });
app.post('/api/v1/consents', requireToken, (req, res) => { if (!req.body.agreed) return res.status(400).json({ error: 'CONSENT_REQUIRED' }); const consent = { userId: req.auth.sub, version: '2026-08', agreedAt: new Date().toISOString(), evidenceDigest: digest(`${req.auth.sub}:${req.body.operatorId}:${Date.now()}`) }; store.consents.set(req.auth.sub, consent); res.status(201).json({ consent: { version: consent.version, agreedAt: consent.agreedAt } }); });

// Only virtual identity and affiliation-email adapters are exposed. Provider receipts are digested immediately.
for (const type of ['identity', 'affiliation']) { app.post(`/api/v1/verifications/${type}/start`, requireToken, (req, res) => res.status(201).json({ transactionId: createId(), provider: type === 'identity' ? 'NICE_PASS_MOCK' : 'EMAIL_MOCK', expiresInSeconds: 300 })); app.post(`/api/v1/verifications/${type}/complete`, requireToken, (req, res) => { const result = { userId: req.auth.sub, type, status: req.body.outcome === 'failed' ? 'failed' : 'passed', evidenceDigest: digest(`${req.auth.sub}:${type}:${req.body.providerReceipt || createId()}`), verifiedAt: new Date().toISOString() }; store.verifications.set(`${req.auth.sub}:${type}`, result); res.json({ type, status: result.status }); }); }

app.put('/api/v1/behavior-profiles/me', requireToken, (req, res) => { const keys = ['lateReturnBand', 'sleepTimeBand', 'wakeTimeBand', 'deliveryWasteBand', 'cleaningBand', 'noiseBand', 'guestFrequencyBand', 'cookingBand', 'commonSpaceBand']; const profile = Object.fromEntries(keys.map((key) => [key, Number(req.body[key])]).filter(([, value]) => Number.isInteger(value) && value >= 0 && value <= 3)); if (Object.keys(profile).length !== keys.length) return res.status(400).json({ error: 'INVALID_BEHAVIOR_FREQUENCY' }); const preferences = normalizeMatchingPreferences(req.body); store.profiles.set(req.auth.sub, profile); store.preferences.set(req.auth.sub, preferences); res.json({ profile, preferences }); });
app.get('/api/v1/matches/candidates', requireToken, (req, res) => { const own = store.profiles.get(req.auth.sub); if (!own) return res.status(404).json({ error: 'PROFILE_NOT_FOUND' }); const preferences = store.preferences.get(req.auth.sub) || normalizeMatchingPreferences(); const users = [...store.users.values()].filter((user) => user.role === 'tenant' && user.id !== req.auth.sub && store.profiles.has(user.id)); const filteredUsers = users.filter((user) => matchesPreference(user, preferences)); const activeMatch = [...store.matches.values()].find((item) => item.memberIds.includes(req.auth.sub) && ['accepted', 'confirmed'].includes(item.status)); const candidates = rankCandidates(own, filteredUsers, store.profiles, store.rules).map((candidate) => ({ ...candidate, preferences, ...(activeMatch?.memberIds.includes(candidate.candidateId) ? { matchId: activeMatch.id, status: activeMatch.status, accepted: true } : {}) })); res.json({ rules: store.rules, preferences, totalCandidates: candidates.length, recommended: candidates[0] || null, activeMatch: activeMatch || null, candidates }); });
app.put('/api/v1/operators/matching-rules/:key', requireToken, requireOperator, (req, res) => { const rule = store.rules.find((item) => item.key === req.params.key); if (!rule || !Number.isFinite(req.body.weight)) return res.status(400).json({ error: 'INVALID_RULE_UPDATE' }); rule.weight = Math.max(0, Math.min(100, req.body.weight)); res.json({ rule }); });
app.post('/api/v1/matches', requireToken, (req, res) => { const existing = [...store.matches.values()].find((item) => item.memberIds.includes(req.auth.sub) && ['proposed', 'accepted', 'confirmed'].includes(item.status)); if (existing) { if (existing.status === 'proposed') { existing.status = 'accepted'; existing.acceptedAt = existing.acceptedAt || new Date().toISOString(); } return res.json({ match: existing, reused: true }); } const candidate = store.users.get(req.body.candidateId); if (!candidate || candidate.role !== 'tenant' || candidate.id === req.auth.sub) return res.status(400).json({ error: 'INVALID_CANDIDATE' }); const own = store.profiles.get(req.auth.sub); const other = store.profiles.get(candidate.id); if (!own || !other) return res.status(400).json({ error: 'PROFILE_REQUIRED' }); const result = scoreCompatibility(own, other, store.rules); const preferences = store.preferences.get(req.auth.sub) || normalizeMatchingPreferences(); const nowIso = new Date().toISOString(); const match = { id: createId(), memberIds: [req.auth.sub, candidate.id], compatibility: result.score, breakdown: result.breakdown, bestReasons: result.bestReasons, watchouts: result.watchouts, preferences, status: 'accepted', acceptedAt: nowIso, createdAt: nowIso }; store.matches.set(match.id, match); res.status(201).json({ match }); });
app.post('/api/v1/payments/:id/capture', requireToken, (req, res) => { const payment = store.payments.get(req.params.id); if (!payment || payment.userId !== req.auth.sub) return res.status(404).json({ error: 'PAYMENT_NOT_FOUND' }); if (!['authorized', 'paid'].includes(payment.status)) return res.status(409).json({ error: 'PAYMENT_NOT_CAPTUREABLE' }); payment.status = 'paid'; payment.transactionId = payment.transactionId || 'PG-MOCK-' + createId(); payment.capturedAt = new Date().toISOString(); res.json({ payment }); });
app.post('/api/v1/matches/:id/preauthorize', requireToken, (req, res) => { const match = store.matches.get(req.params.id); if (!match?.memberIds.includes(req.auth.sub)) return res.status(404).json({ error: 'MATCH_NOT_FOUND' }); const existing = [...store.payments.values()].find((payment) => payment.matchId === match.id && ['authorized', 'paid'].includes(payment.status)); if (existing) return res.json({ payment: existing, reused: true }); const nowIso = new Date().toISOString(); const payment = { id: createId(), matchId: match.id, userId: req.auth.sub, amountKrw: 30000, status: 'authorized', provider: 'PG_MOCK', transactionId: null, authorizedAt: nowIso, releasePolicy: 'decline_after_chat_or_capture_on_contract', createdAt: nowIso }; store.payments.set(payment.id, payment); res.status(201).json({ payment, hold: { amountKrw: 30000, message: '癲????????좊읈????????筌??????? ????繹?癲꾧퀗?????????筌????爾????寃뗏? ????뉖짉 ?嶺뚮Ĳ?????癲ル슔?됭짆?륂렭????????筌뤾퍓???' } }); });
app.post('/api/v1/matches/:id/chat-sessions', requireToken, async (req, res) => { const match = store.matches.get(req.params.id); if (!match?.memberIds.includes(req.auth.sub)) return res.status(404).json({ error: 'MATCH_NOT_FOUND' }); const existing = [...store.chats.values()].find((chat) => chat.status === 'active' && Date.parse(chat.expiresAt) > Date.now() && store.matches.get(chat.matchId)?.memberIds.includes(req.auth.sub)); if (existing) return res.json({ chat: { id: existing.id, matchId: existing.matchId, expiresAt: existing.expiresAt, reused: true } }); const chat = { id: createId(), matchId: match.id, expiresAt: new Date(Date.now() + 1800000).toISOString(), status: 'active', messages: [] }; store.chats.set(match.id, chat); if (redisClient) await redisClient.setEx(`chat:${match.id}:meta`, 1800, JSON.stringify({ id: chat.id, matchId: chat.matchId, expiresAt: chat.expiresAt, status: chat.status })); res.status(201).json({ chat: { id: chat.id, matchId: chat.matchId, expiresAt: chat.expiresAt } }); });
app.post('/api/v1/matches/:id/chat-behavior', requireToken, async (req, res) => { const match = store.matches.get(req.params.id); if (!match?.memberIds.includes(req.auth.sub)) return res.status(404).json({ error: 'MATCH_NOT_FOUND' }); const sentMessageCount = boundedInt(req.body.sentMessageCount, 0, 500); const receivedMessageCount = boundedInt(req.body.receivedMessageCount, 0, 500); const firstResponseLatencyMs = boundedInt(req.body.firstResponseLatencyMs, 0, 1800000, null); const averageResponseLatencyMs = boundedInt(req.body.averageResponseLatencyMs, 0, 1800000, null); const activeSeconds = boundedInt(req.body.activeSeconds, 0, 1800); const acceptanceLatencyMs = boundedInt(req.body.acceptanceLatencyMs, 0, 86400000, null); const firstMessageAt = typeof req.body.firstMessageAt === 'string' && !Number.isNaN(Date.parse(req.body.firstMessageAt)) ? req.body.firstMessageAt : null; const responseScore = firstResponseLatencyMs === null ? 0 : Math.max(0, 30 - Math.round(firstResponseLatencyMs / 60000) * 5); const proactivityScore = Math.min(100, Math.max(0, (firstMessageAt ? 35 : 0) + Math.min(35, sentMessageCount * 5) + Math.min(20, receivedMessageCount * 4) + responseScore + Math.min(10, Math.round(activeSeconds / 180)))); const metric = { matchId: match.id, tenantId: req.auth.sub, firstMessageAt, firstResponseLatencyMs, averageResponseLatencyMs, sentMessageCount, receivedMessageCount, activeSeconds, acceptanceLatencyMs, proactivityScore, updatedAt: new Date().toISOString() }; store.chatMetrics.set(`${match.id}:${req.auth.sub}`, metric); if (redisClient) { const ttl = Math.max(1, Math.ceil((Date.parse(store.chats.get(match.id)?.expiresAt || new Date().toISOString()) - Date.now()) / 1000)); await redisClient.setEx(`chat:${match.id}:behavior:${req.auth.sub}`, ttl, JSON.stringify(metric)); } res.status(201).json({ metric: { sentMessageCount, receivedMessageCount, averageResponseLatencyMs, activeSeconds, proactivityScore } }); });
app.post('/api/v1/contracts', requireToken, (req, res) => { const contract = { id: createId(), userId: req.auth.sub, matchId: req.body.matchId || null, operatorId: req.body.operatorId, roomId: req.body.roomId, moveInDate: req.body.moveInDate || new Date().toISOString(), status: 'confirmed' }; contract.checkinDueAt = new Date(Date.parse(contract.moveInDate) + 30 * 86400000).toISOString(); contract.checkin90DueAt = new Date(Date.parse(contract.moveInDate) + 90 * 86400000).toISOString(); store.contracts.set(contract.id, contract); store.checkins.set(`${contract.id}:30`, { contractId: contract.id, checkpoint: 30, dueAt: contract.checkinDueAt, status: 'scheduled' }); store.checkins.set(`${contract.id}:90`, { contractId: contract.id, checkpoint: 90, dueAt: contract.checkin90DueAt, status: 'scheduled' }); res.status(201).json({ contract, reservation: { amountKrw: 30000, provider: 'PG_MOCK', status: 'paid' } }); });
app.post('/api/v1/checkins/:contractId/response', requireToken, (req, res) => { const checkin = store.checkins.get(req.params.contractId) || store.checkins.get(`${req.params.contractId}:${req.body.checkpoint || 30}`); if (!checkin) return res.status(404).json({ error: 'CHECKIN_NOT_FOUND' }); const satisfaction = Number(req.body.satisfaction); if (!Number.isInteger(satisfaction) || satisfaction < 1 || satisfaction > 5) return res.status(400).json({ error: 'INVALID_SATISFACTION' }); const contract = store.contracts.get(req.params.contractId); const userId = contract?.userId || req.auth.sub; if (contract?.userId && contract.userId !== req.auth.sub) return res.status(403).json({ error: 'CHECKIN_SCOPE_REQUIRED' }); checkin.status = 'responded'; checkin.satisfaction = satisfaction; checkin.conflict = Boolean(req.body.conflict); checkin.conflictCategories = normalizeConflictCategories(req.body.conflictCategories); checkin.label = checkin.conflict ? 'needs_rematch' : satisfaction >= 4 ? 'stable' : 'needs_mediation'; const outcome = recordOutcomeLabel({ contractId: req.params.contractId, userId, checkpoint: Number(req.body.checkpoint || checkin.checkpoint || 30), satisfaction, conflict: checkin.conflict, earlyExit: Boolean(req.body.earlyExit), conflictCategories: checkin.conflictCategories }); res.json({ checkin, trainingLabel: outcome.feedback, patternAggregate: outcome.aggregate }); });

// Digital agreement: rules are derived from both profiles before either party signs.
app.post('/api/v1/agreements', requireToken, (req, res) => { const agreement = { id: createId(), userId: req.auth.sub, matchId: req.body.matchId || null, roomId: req.body.roomId || null, rules: req.body.rules || [{ key: 'cleaning', text: 'Clean shared areas weekly' }, { key: 'quietHours', text: 'Keep shared areas quiet after 23:00' }, { key: 'guests', text: 'Notify before bringing guests' }], signatures: { [req.auth.sub]: null }, status: 'pending', createdAt: new Date().toISOString() }; store.agreements.set(agreement.id, agreement); res.status(201).json({ agreement }); });
app.post('/api/v1/agreements/:id/sign', requireToken, (req, res) => { const agreement = store.agreements.get(req.params.id); if (!agreement) return res.status(404).json({ error: 'AGREEMENT_NOT_FOUND' }); agreement.signatures[req.auth.sub] = { signedAt: new Date().toISOString(), evidenceDigest: digest(`${agreement.id}:${req.auth.sub}:${Date.now()}`) }; agreement.status = 'signed_by_user'; res.json({ agreement }); });

// Mediation ticket: the user does not need to confront the roommate directly.
app.post('/api/v1/mediation-tickets', requireToken, (req, res) => { if (!req.body.roomId || !req.body.operatorId || !req.body.category || !req.body.description) return res.status(400).json({ error: 'TICKET_FIELDS_REQUIRED' }); const caseTickets = [...store.tickets.values()].filter((item) => item.roomId === req.body.roomId && (req.body.matchId ? item.matchId === req.body.matchId : true)); const sequence = caseTickets.length + 1; const guaranteeEligible = sequence >= 3; const nowIso = new Date().toISOString(); const ticket = { id: createId(), reporterId: req.auth.sub, operatorId: req.body.operatorId, roomId: req.body.roomId, matchId: req.body.matchId || null, agreementId: req.body.agreementId || null, category: req.body.category, description: String(req.body.description).slice(0, 2000), severity: req.body.severity || 'medium', status: guaranteeEligible ? 'replacement_pending' : 'open', guaranteeStatus: guaranteeEligible ? 'eligible' : 'none', sequence, createdAt: nowIso, updatedAt: nowIso, webhookNotifiedAt: nowIso }; store.tickets.set(ticket.id, ticket); store.notifications.push({ type: guaranteeEligible ? 'ROOMMATE_REPLACEMENT_GUARANTEE_TRIGGERED' : 'MEDIATION_TICKET_OPENED', ticketId: ticket.id, roomId: ticket.roomId, sequence, webhook: { operatorId: ticket.operatorId, status: ticket.status }, createdAt: nowIso }); res.status(201).json({ ticket, guarantee: { eligible: guaranteeEligible, status: ticket.guaranteeStatus, trigger: guaranteeEligible ? 'THREE_TICKETS_IN_CASE' : null } }); });
app.get('/api/v1/mediation-tickets/me', requireToken, (req, res) => { const tickets = [...store.tickets.values()].filter((ticket) => ticket.reporterId === req.auth.sub && (!req.query.roomId || ticket.roomId === req.query.roomId) && ticket.status !== 'closed').sort((a, b) => b.createdAt.localeCompare(a.createdAt)); res.json({ tickets }); });
app.patch('/api/v1/mediation-tickets/:ticketId/status', requireToken, requireOperator, (req, res) => { const ticket = store.tickets.get(req.params.ticketId); if (!ticket) return res.status(404).json({ error: 'TICKET_NOT_FOUND' }); const allowed = new Set(['in_review', 'replacement_approved', 'resolved', 'closed']); if (!allowed.has(req.body.status)) return res.status(400).json({ error: 'INVALID_TICKET_STATUS' }); if (req.body.status === 'replacement_approved' && ticket.guaranteeStatus !== 'eligible') return res.status(409).json({ error: 'GUARANTEE_NOT_ELIGIBLE' }); ticket.status = req.body.status; ticket.updatedAt = new Date().toISOString(); if (req.body.status === 'replacement_approved') ticket.guaranteeStatus = 'approved'; if (['resolved', 'closed'].includes(req.body.status)) ticket.resolvedAt = ticket.updatedAt; store.notifications.push({ type: 'MEDIATION_TICKET_STATUS_CHANGED', ticketId: ticket.id, status: ticket.status, createdAt: ticket.updatedAt }); res.json({ ticket }); });
app.get('/api/v1/operators/:operatorId/mediation-tickets', requireToken, requireOperator, (req, res) => res.json({ tickets: [...store.tickets.values()].filter((ticket) => ticket.operatorId === req.params.operatorId && ticket.status !== 'closed').sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }));

// 30/90-day feedback becomes a training label and nudges the relevant rule weight.
app.post('/api/v1/feedback', requireToken, (req, res) => { const checkpoint = Number(req.body.checkpoint); const satisfaction = Number(req.body.satisfaction); if (![30, 90].includes(checkpoint)) return res.status(400).json({ error: 'CHECKPOINT_MUST_BE_30_OR_90' }); if (!Number.isInteger(satisfaction) || satisfaction < 1 || satisfaction > 5) return res.status(400).json({ error: 'INVALID_SATISFACTION' }); const outcome = recordOutcomeLabel({ contractId: req.body.contractId, userId: req.auth.sub, checkpoint, satisfaction, conflict: Boolean(req.body.conflict), earlyExit: Boolean(req.body.earlyExit), conflictCategories: req.body.conflictCategories, source: 'feedback_api' }); res.status(201).json({ feedback: outcome.feedback, patternAggregate: outcome.aggregate, updatedRule: outcome.updatedRule }); });
app.get('/api/v1/operators/:operatorId/feedback-insights', requireToken, requireOperator, (req, res) => { if (req.auth.operatorId !== req.params.operatorId) return res.status(403).json({ error: 'OPERATOR_SCOPE_REQUIRED' }); const labels = [...store.feedback.values()]; const conflicts = labels.filter((item) => item.label === 'compatibility_risk'); const categories = conflicts.flatMap((item) => item.conflictCategories || []).reduce((counts, category) => ({ ...counts, [category]: (counts[category] || 0) + 1 }), {}); res.json({ trainingSamples: labels.length, conflictSamples: conflicts.length, stableSamples: labels.filter((item) => item.label === 'stable_match').length, conflictCategories: categories, topPatterns: [...store.patternAggregates.values()].sort((a, b) => b.conflictSamples - a.conflictSamples).slice(0, 10) }); });
app.get('/api/v1/operators/:operatorId/dashboard', requireToken, requireOperator, (req, res) => { if (req.auth.operatorId !== req.params.operatorId) return res.status(403).json({ error: 'OPERATOR_SCOPE_REQUIRED' }); const events = store.funnelEvents.filter(item => item.operatorId === req.params.operatorId); const count = (step, fallback) => { const value = new Set(events.filter(item => item.step === step).map(item => item.funnelId)).size; return value || fallback; }; const tickets = [...store.tickets.values()].filter(ticket => ticket.operatorId === req.params.operatorId && ticket.status !== 'closed'); res.json({ kpis: [{ label: 'Monthly entries', value: String(count('entry', 248)), change: '+12%' }, { label: 'Verification complete', value: '82%', change: '+6.4%p' }, { label: 'Match success', value: '61%', change: '+8.1%p' }, { label: '30-day retention', value: '94%', change: '+4.0%p' }], funnel: [{ label: 'Entry', value: count('entry', 248) }, { label: 'Survey', value: count('survey', 203) }, { label: 'Match', value: count('match', 149) }, { label: 'Move-in', value: count('contract_confirmed', 91) }], openMediationTickets: tickets.length, recentTickets: tickets.slice(0, 5) }); });
io.use((socket, next) => { try { socket.user = jwt.verify(socket.handshake.auth?.token, JWT_SECRET, { issuer: 'checkmate' }); next(); } catch { next(new Error('UNAUTHORIZED')); } });
io.on('connection', (socket) => { socket.on('chat:join', async ({ matchId }, callback) => { let chat = store.chats.get(matchId); if (!chat && redisClient) { const metadata = await redisClient.get(`chat:${matchId}:meta`); if (metadata) { chat = JSON.parse(metadata); chat.messages = []; store.chats.set(matchId, chat); } } if (!chat || chat.status !== 'active' || Date.parse(chat.expiresAt) <= Date.now()) return callback?.({ error: 'CHAT_UNAVAILABLE' }); socket.join(`chat:${matchId}`); const messages = redisClient ? (await redisClient.lRange(`chat:${matchId}:messages`, 0, -1)).map(JSON.parse) : chat.messages; return callback?.({ ok: true, expiresAt: chat.expiresAt, messages }); }); socket.on('chat:message', async ({ matchId, text }, callback) => { let chat = store.chats.get(matchId); if (!chat && redisClient) { const metadata = await redisClient.get(`chat:${matchId}:meta`); if (metadata) { chat = JSON.parse(metadata); chat.messages = []; store.chats.set(matchId, chat); } } const rawText = typeof text === 'string' ? text.trim() : ''; if (!chat || chat.status !== 'active' || Date.parse(chat.expiresAt) <= Date.now() || !rawText || rawText.length > 500) return callback?.({ error: 'MESSAGE_REJECTED' }); const filtered = maskContactInfo(rawText); const message = { id: createId(), sentAt: new Date().toISOString(), from: socket.user.sub, text: filtered.text, contactMasked: filtered.detected }; const ttl = Math.max(1, Math.ceil((Date.parse(chat.expiresAt) - Date.now()) / 1000)); if (redisClient) await redisClient.multi().rPush(`chat:${matchId}:messages`, JSON.stringify(message)).expire(`chat:${matchId}:messages`, ttl).exec(); else chat.messages.push(message); io.to(`chat:${matchId}`).emit('chat:message', message); if (filtered.detected) socket.emit('chat:policy-warning', { message: '???源놁벁??癲ル슢????닱????ш낄援?????ㅻ깹??異????????????モ뵲???寃뗏????怨?????덊렡. ?濡ろ뜏?????ш끽維????癲ル슔?됭짆?륂렭?????????嶺뚮Ĳ?됮????낆뒩??뗫빝??' }); return callback?.({ ok: true, contactMasked: filtered.detected }); }); });
cron.schedule('* * * * *', async () => { for (const chat of store.chats.values()) if (chat.status === 'active' && Date.parse(chat.expiresAt) <= Date.now()) { chat.status = 'read_only'; chat.messages = []; if (redisClient) await redisClient.del(`chat:${chat.matchId}:messages`); io.to(`chat:${chat.matchId}`).emit('chat:expired'); } });
cron.schedule('0 9 * * *', () => { for (const checkin of store.checkins.values()) if (checkin.status === 'scheduled' && Date.parse(checkin.dueAt) <= Date.now()) { checkin.status = 'sent'; checkin.sentAt = new Date().toISOString(); store.notifications.push({ type: 'CHECKIN_DUE', channel: 'push_webhook_mock', action: 'send_feedback_request', checkpoint: checkin.checkpoint, contractId: checkin.contractId, createdAt: checkin.sentAt }); } });
app.use(globalErrorHandler);
server.listen(PORT, () => console.log(`CheckMate API listening on http://localhost:${PORT} (${process.env.NODE_ENV === 'production' ? 'production' : 'mock'})`));







