import { React, useEffect, useState, API, responseJson, ChevronLeft, MessageCircle, Check } from '../shared.js';
import './chat-inbox.css';

export default function ChatInbox({ auth, back, onOpen }) {
  const [requests, setRequests] = useState([]), [rooms, setRooms] = useState([]), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const headers = { Authorization: `Bearer ${auth.accessToken}`, 'Content-Type': 'application/json' };
  const load = async () => { try { const [requestData, roomData] = await Promise.all([responseJson(await fetch(`${API}/api/v1/chat/requests`, { headers })), responseJson(await fetch(`${API}/api/v1/chat/rooms`, { headers }))]); setRequests(requestData.requests || []); setRooms(roomData.rooms || []); } catch (e) { setError(e.message || '채팅 목록을 불러오지 못했습니다.'); } };
  useEffect(() => { load(); }, [auth.accessToken]);
  const accept = async (id) => { setBusy(id); setError(''); try { await responseJson(await fetch(`${API}/api/v1/chat/requests/${id}/accept`, { method: 'POST', headers })); await load(); } catch (e) { setError(e.message || '요청을 수락하지 못했습니다.'); } finally { setBusy(''); } };
  const open = async (room) => { setBusy(room.matchId); setError(''); try { const data = await responseJson(await fetch(`${API}/api/v1/matches/${room.matchId}/chat-sessions`, { method: 'POST', headers })); onOpen({ ...data.chat, matchId: room.matchId }); } catch (e) { setError(e.message || '채팅방을 열지 못했습니다.'); } finally { setBusy(''); } };
  return <section className="page-pad inner-page chat-inbox"><button className="back-button" onClick={back}><ChevronLeft size={19}/>뒤로</button><div className="section-kicker">채팅 센터</div><h2>채팅 요청과<br/>내 채팅방</h2>{error && <p className="login-error">{error}</p>}<div className="inbox-section"><h3>받은 채팅 요청 <span>{requests.length}</span></h3>{requests.length ? requests.map((request) => <div className="inbox-card" key={request.id}><div className="inbox-avatar"><MessageCircle size={18}/></div><div><strong>익명 사용자</strong><small>안심 채팅을 요청했습니다</small></div><button className="primary-button inbox-action" onClick={() => accept(request.id)} disabled={busy === request.id}>{busy === request.id ? '처리 중' : <><Check size={15}/>수락</>}</button></div>) : <p className="inbox-empty">받은 채팅 요청이 없습니다.</p>}</div><div className="inbox-section"><h3>내 채팅방 <span>{rooms.length}</span></h3>{rooms.length ? rooms.map((room) => <button className="inbox-card inbox-room" key={room.matchId} onClick={() => open(room)} disabled={busy === room.matchId}><div className="inbox-avatar"><MessageCircle size={18}/></div><div><strong>{room.partner?.pseudonym || '익명 사용자'}</strong><small>{room.chat ? '30분 안심 채팅 이어가기' : '채팅방 입장하기'}</small></div><span>›</span></button>) : <p className="inbox-empty">서로 수락하면 이곳에 채팅방이 생성됩니다.</p>}</div></section>;
}
