import { React, useEffect, useRef, useState, API, io, ChevronLeft, CreditCard, LockKeyhole, Send, ShieldCheck, ArrowRight } from '../shared.js';

export default function Chat({ auth, chat, back, confirm }) {
  const [remaining, setRemaining] = useState(chat ? Math.max(0, Math.floor((Date.parse(chat.expiresAt) - Date.now()) / 1000)) : 1800);
  const [messages, setMessages] = useState([]), [text, setText] = useState(''), [online, setOnline] = useState(false), [policyNotice, setPolicyNotice] = useState('');
  const socketRef = useRef(null);
  useEffect(() => { if (!chat) return; const socket = io(API, { auth: { token: auth.accessToken } }); socketRef.current = socket; const join = () => socket.emit('chat:join', { matchId: chat.matchId }, (result) => { if (result?.ok) { setOnline(true); if (result.messages?.length) setMessages(result.messages); } else { setOnline(false); setTimeout(() => socket.connected && join(), 350); } }); socket.on('connect', join); socket.on('disconnect', () => setOnline(false)); socket.on('chat:message', (message) => setMessages((items) => items.some((item) => item.id === message.id) ? items : [...items, message])); socket.on('chat:policy-warning', (result) => setPolicyNotice(result?.message || 'Contact exchange is restricted for safety.')); return () => socket.close(); }, [auth.accessToken, chat?.matchId]);
  useEffect(() => { const timer = setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, []);
  if (!chat) return <section className="page-pad inner-page"><h2>No active chat.</h2><button className="primary-button" onClick={back}>Back to matching</button></section>;
  const send = () => { if (!text.trim() || !online || !remaining) return; socketRef.current?.emit('chat:message', { matchId: chat.matchId, text: text.trim() }); setText(''); };
  return <section className="chat-page"><header className="chat-top"><button className="back-button" onClick={back}><ChevronLeft size={19}/>Matching</button><div><strong>Anonymous tenant</strong><span>{online ? 'Live connection' : 'Connecting...'}</span></div><b>{String(Math.floor(remaining / 60)).padStart(2, '0')}:{String(remaining % 60).padStart(2, '0')}</b></header><div className="chat-policy"><LockKeyhole size={13}/>This chat is limited to one matched roommate and expires automatically.</div>{policyNotice && <div className="chat-guard-notice"><ShieldCheck size={14}/>{policyNotice}</div>}<div className="chat-benefit-warning"><ShieldCheck size={14}/>Complete chat and payment inside CheckMate to keep 30-day care and roommate replacement coverage.</div><div className="preauth-note"><CreditCard size={13}/>30,000 KRW is pre-authorized before chat.</div><div className="messages">{messages.map((message) => <div className={`bubble ${message.from === auth.user.id ? 'mine' : 'other'}`} key={message.id}>{message.text || message.body}</div>)}</div><div className="chat-input"><input disabled={!remaining || !online} value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} placeholder={online ? 'Write a message' : 'Connecting...'}/><button onClick={send} disabled={!remaining || !online}><Send size={18}/></button></div>{remaining > 0 && !sessionStorage.getItem('cm-care-start') && <button className="primary-button chat-confirm" onClick={confirm}>Finish chat and confirm move-in <ArrowRight size={18}/></button>}</section>;
}
