import { React, useEffect, useRef, useState, API, Send, ShieldCheck, io, responseJson } from '../shared.js';
import './dual-demo.css';


function Pane({ id, name, color, messages, online, onSend }) {
  name = id === 'tenant1' ? '민지' : id === 'tenant2' ? '지연' : name;
  const [text, setText] = useState('');
  const send = () => { const value = text.trim(); if (!value) return; onSend(id, value); setText(''); };
  return <section className="demo-pane"><header><div className="demo-avatar" style={{ background: color }}>{name.slice(-1)}</div><div><strong>{name}</strong><span><i className={online ? 'dual-online-dot' : 'dual-offline-dot'}/>{online ? 'Live connection' : 'Connecting...'} · 30:00</span></div><b>SAFE</b></header><div className="demo-messages">{messages.map((message, index) => <p key={`${message.id || index}`} className={`bubble ${message.from === id ? 'mine' : 'other'}`}>{message.text}</p>)}</div><div className="demo-composer"><input value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && send()} placeholder={online ? 'Write a message' : 'Connecting...'} disabled={!online}/><button onClick={send} aria-label="Send message" disabled={!online}><Send size={17}/></button></div></section>;
}

export default function DualDemo() {
  const [messages, setMessages] = useState([]), [online, setOnline] = useState({ tenant1: false, tenant2: false }), [names, setNames] = useState({ tenant1: '세입자 1', tenant2: '세입자 2' }), [error, setError] = useState('');
  const sockets = useRef({}), sessionRef = useRef(null);
  useEffect(() => { let cancelled = false; async function connect() { try { const login = async (accountId) => responseJson(await fetch(`${API}/api/v1/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ accountId, password: '1234' }) })); const [one, two] = await Promise.all([login('tenant1'), login('tenant2')]); const headers = { Authorization: `Bearer ${one.accessToken}`, 'Content-Type': 'application/json' }; const matchResult = await responseJson(await fetch(`${API}/api/v1/matches`, { method: 'POST', headers, body: JSON.stringify({ candidateId: two.user.id }) })); const matchId = matchResult.match.id; const room = await responseJson(await fetch(`${API}/api/v1/matches/${matchId}/chat-sessions`, { method: 'POST', headers })); sessionRef.current = { matchId, expiresAt: room.chat.expiresAt }; if (cancelled) return; const connectSocket = (id, token) => { const socket = io(API, { auth: { token } }); sockets.current[id] = socket; socket.on('connect', () => socket.emit('chat:join', { matchId }, (result) => { if (result?.messages?.length && id === 'tenant1') setMessages(result.messages.map((item) => ({ id: item.id, from: item.from === one.user.id ? 'tenant1' : 'tenant2', text: item.text }))); setOnline((state) => ({ ...state, [id]: Boolean(result?.ok) })); })); socket.on('chat:message', (message) => setMessages((items) => items.some((item) => item.id === message.id) ? items : [...items, { id: message.id, from: message.from === one.user.id ? 'tenant1' : 'tenant2', text: message.text }])); socket.on('chat:expired', () => setOnline({ tenant1: false, tenant2: false })); socket.on('connect_error', () => setOnline((state) => ({ ...state, [id]: false }))); }; connectSocket('tenant1', one.accessToken); connectSocket('tenant2', two.accessToken); } catch (err) { if (!cancelled) setError(err.message || '듀얼 채팅을 연결하지 못했습니다.'); } } connect(); return () => { cancelled = true; Object.values(sockets.current).forEach((socket) => socket?.close()); sockets.current = {}; }; }, []);
  const send = (id, text) => { const socket = sockets.current[id]; if (socket && sessionRef.current) socket.emit('chat:message', { matchId: sessionRef.current.matchId, text }); };
  return <main className="dual-demo"><header className="dual-header"><div><span className="section-kicker">CHECKMATE DUAL DEMO</span><h1>Two tenants. One safer move-in.</h1><p>실제 Socket.IO 채팅방에 두 데모 계정이 연결되어 있습니다.</p></div><span className="dual-live"><i/>LIVE MATCH · REDIS</span></header>{error && <p className="dual-error">{error}</p>}<div className="dual-panes"><Pane id="tenant1" name="Tenant 1" color="#dcecf1" messages={messages} online={online.tenant1} onSend={send}/><Pane id="tenant2" name="Tenant 2" color="#eee4ff" messages={messages} online={online.tenant2} onSend={send}/></div><p className="dual-demo-note"><ShieldCheck size={15}/> 한쪽에서 보낸 메시지는 Express·Socket.IO·Redis를 거쳐 상대 화면에 표시됩니다.</p></main>;
}
