import { React, useEffect, useState, BadgeCheck, ChevronLeft, LogOut, UserRound, API, responseJson } from '../shared.js';
import './mypage.css';

export default function MyPage({ auth, back, logout, onAuthUpdated }) {
  const [form, setForm] = useState({ pseudonym: auth.user.pseudonym || '', email: '', age: '', gender: '' });
  const [editing, setEditing] = useState(false), [saving, setSaving] = useState(false), [notice, setNotice] = useState('');
  useEffect(() => { fetch(`${API}/api/v1/users/me`, { headers: { Authorization: `Bearer ${auth.accessToken}` } }).then(responseJson).then(({ user }) => setForm({ pseudonym: user.pseudonym || '', email: user.email || '', age: user.age || '', gender: user.gender || '' })).catch(() => {}); }, [auth.accessToken]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); setNotice(''); try { const data = await responseJson(await fetch(`${API}/api/v1/users/me`, { method: 'PATCH', headers: { Authorization: `Bearer ${auth.accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify(form) })); const nextAuth = { ...auth, user: { ...auth.user, ...data.user } }; sessionStorage.setItem('cm-auth', JSON.stringify(nextAuth)); onAuthUpdated?.(nextAuth); setEditing(false); setNotice('프로필이 저장되었습니다.'); } catch { setNotice('프로필을 저장하지 못했습니다. 입력값을 확인해 주세요.'); } finally { setSaving(false); } };
  return <section className="page-pad inner-page my-page"><button className="back-button" onClick={back}><ChevronLeft size={19}/>Back</button><div className="section-kicker">MY CHECKMATE</div><h2>My profile<br/>and safety settings</h2><div className="my-profile-card"><div className="my-profile-avatar"><UserRound size={31}/></div><div><strong>{form.pseudonym || 'Tenant'}</strong><span>Tenant account</span></div><BadgeCheck size={22}/></div>{editing ? <form className="profile-edit-form" onSubmit={save}><label>Nickname<input value={form.pseudonym} onChange={(e) => update('pseudonym', e.target.value)} maxLength={80} required/></label><label>Email<input type="email" value={form.email} onChange={(e) => update('email', e.target.value)} placeholder="optional@example.com"/></label><label>Age<input type="number" min="18" max="100" value={form.age} onChange={(e) => update('age', e.target.value)} placeholder="optional"/></label><label>Gender<select value={form.gender} onChange={(e) => update('gender', e.target.value)}><option value="">Prefer not to say</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option></select></label><div className="profile-edit-actions"><button type="button" className="secondary-button" onClick={() => setEditing(false)}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button></div></form> : <><div className="my-account-note"><span>Account ID</span><strong>{auth.user.accountId}</strong></div><button className="secondary-button profile-edit-button" onClick={() => setEditing(true)}>Edit my information</button></>}{notice && <p className="profile-notice">{notice}</p>}<button className="logout-button" onClick={logout}><LogOut size={18}/>Log out</button></section>}
