import { React, useEffect, useState, initialAnswers, API, embed, event, responseJson, Home, UsersRound, MessageCircle, UserRound, CalendarDays } from './shared.js';
import { localizeKorean } from './i18n/korean.js';
import Login from './components/Login.jsx';
import Entry from './components/Entry.jsx';
import Survey from './components/Survey.jsx';
import Match from './components/Match.jsx';
import Chat from './components/Chat.jsx';
import AgreementDraftPage from './components/AgreementDraftPage.jsx';
import ChatInbox from './components/ChatInbox.jsx';
import Confirm from './components/Confirm.jsx';
import CarePage from './components/CarePage.jsx';
import MyPage from './components/MyPage.jsx';
import Dashboard from './components/Dashboard.jsx';
import RoomLoungeMap from './components/RoomLoungeMap.jsx';
import CalendarPage from './components/Calendar.jsx';
import VariantSelect from './components/VariantSelect.jsx';
import { readVariantContext, VARIANT_CONTEXT_KEY } from './variants.js';
import './components/lounge.css';

export default function App(){
 const mapEditor=typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('mapEditor')==='true';
 const[variantContext,setVariantContext]=useState(readVariantContext);
 if(mapEditor)return <StandaloneMapEditor/>;
 if(!variantContext)return <VariantSelect onSelect={setVariantContext}/>;
 const changeVariant=()=>{sessionStorage.removeItem(VARIANT_CONTEXT_KEY);sessionStorage.removeItem('cm-auth');setVariantContext(null)};
 return <AuthenticatedApp variantContext={variantContext} onChangeVariant={changeVariant}/>;
}

function StandaloneMapEditor(){
 return <div className="standalone-map-editor"><header><img src="/checkmate-logo.svg" alt="CheckMate"/><div><strong>CheckMate Pixel Studio</strong><span>로그인 없이 라운지 맵을 편집합니다.</span></div></header><main><RoomLoungeMap/></main></div>;
}

function AuthenticatedApp({variantContext,onChangeVariant}){
 const[context]=useState(embed),[auth,setAuth]=useState(()=>JSON.parse(sessionStorage.getItem('cm-auth')||'null')),[page,setPage]=useState('entry'),[consent,setConsent]=useState(false),[profileComplete,setProfileComplete]=useState(false),[questionPage,setQuestionPage]=useState(0),[answers,setAnswers]=useState({...initialAnswers}),[match,setMatch]=useState(()=>{try{const a=JSON.parse(sessionStorage.getItem('cm-auth')||'null');return a?.user?.id?JSON.parse(sessionStorage.getItem('cm-match-'+a.user.id)||'null'):null}catch{return null}}),[chat,setChat]=useState(null),[chatType,setChatType]=useState('PRE_MOVE'),[agreementContext,setAgreementContext]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const headers={Authorization:'Bearer '+auth?.accessToken,'Content-Type':'application/json','X-CheckMate-Variant':variantContext.id};
 useEffect(()=>{document.documentElement.classList.remove('dark');localStorage.removeItem('cm-theme')},[]);
 useEffect(()=>{event(context,'entry')},[context]); useEffect(()=>{const reset=()=>{sessionStorage.removeItem('cm-auth');setAuth(null);setMatch(null);setChat(null);setAgreementContext(null);setPage('entry')};window.addEventListener('cm-auth-expired',reset);return()=>window.removeEventListener('cm-auth-expired',reset)},[]); useEffect(()=>{const run=()=>setTimeout(localizeKorean,0);const observer=new MutationObserver(run);observer.observe(document.body,{childList:true,subtree:true});run();return()=>observer.disconnect()},[auth]);
 useEffect(()=>{if(auth?.user?.id&&match)sessionStorage.setItem('cm-match-'+auth.user.id,JSON.stringify(match))},[auth?.user?.id,match]);
 useEffect(()=>{if(!auth?.accessToken||auth.user.role!=='tenant')return;fetch(API+'/api/v1/behavior-profiles/me',{headers}).then(responseJson).then(data=>{const savedVariant=data.profile?._meta?.variant;setProfileComplete(Boolean(data.completed&&(!savedVariant||savedVariant===variantContext.id)));if(data.profile) setAnswers(old=>({...old,...data.profile,_meta:undefined}))}).catch(()=>setProfileComplete(false))},[auth?.accessToken,auth?.user?.role,variantContext.id]);
 useEffect(()=>{if(!auth?.accessToken)return;let cancelled=false;const key=`cm-care-start-${auth.user.id}`;const sync=async()=>{try{const data=await responseJson(await fetch(API+'/api/v1/matches/candidates',{headers,cache:'no-store'}));if(cancelled)return;const state=data.activeMatch||data.pendingMatch;if(!state){sessionStorage.removeItem(key);setMatch(null);setChat(null);return}const source=data.candidates?.find(c=>state.memberIds.includes(c.candidateId))||{candidateId:state.memberIds.find(id=>id!==auth.user.id),pseudonym:'Anonymous tenant',score:state.compatibility,breakdown:state.breakdown,bestReasons:state.bestReasons,watchouts:state.watchouts,preferences:state.preferences};const status=String(state.status||'').toLowerCase();const restored={...source,...state,matchId:state.id,status,accepted:['accepted','confirmed'].includes(status),totalCandidates:data.totalCandidates||data.candidates?.length||0};setMatch(restored);if(status==='confirmed'){try{const payment=await responseJson(await fetch(`${API}/api/v1/matches/${state.id}/payment-status`,{headers:{Authorization:'Bearer '+auth.accessToken},cache:'no-store'}));if(payment.allTenantsPaid){const startAt=sessionStorage.getItem(key)||payment.payment?.paidAt||new Date().toISOString();sessionStorage.setItem(key,startAt)}else sessionStorage.removeItem(key)}catch{sessionStorage.removeItem(key)}}else sessionStorage.removeItem(key)}catch{}};sync();const timer=setInterval(sync,4000);return()=>{cancelled=true;clearInterval(timer)}},[auth?.accessToken,variantContext.id]);
 useEffect(()=>{if(!auth?.accessToken||!match?.matchId||!['accepted','confirmed'].includes(String(match.status).toLowerCase())||chat)return;fetch(`${API}/api/v1/matches/${match.matchId}/chat-sessions`,{method:'POST',headers,body:JSON.stringify({type:'PRE_MOVE'})}).then(responseJson).then(data=>setChat({...data.chat,matchId:match.matchId})).catch(()=>{})},[auth?.accessToken,match?.matchId,match?.status,chat]);
 useEffect(()=>{if(!auth?.accessToken||!match?.matchId||String(match.status).toLowerCase()!=='confirmed')return;let cancelled=false;responseJson(fetch(`${API}/api/v1/matches/${match.matchId}/payment-status`,{headers:{Authorization:'Bearer '+auth.accessToken},cache:'no-store'})).then(data=>{if(!cancelled&&!data.allTenantsPaid)setMatch(old=>old?.matchId===match.matchId?{...old,status:'accepted',accepted:true}:old)}).catch(()=>{});return()=>{cancelled=true}},[auth?.accessToken,match?.matchId,match?.status]);
 const go=next=>{setPage(next);event(context,next)};
 const login=result=>{sessionStorage.removeItem(`cm-care-start-${result.user.id}`);sessionStorage.removeItem('cm-match-'+result.user.id);sessionStorage.setItem('cm-auth',JSON.stringify({...result,variant:variantContext.id}));setMatch(null);setChat(null);setAuth({...result,variant:variantContext.id});setPage(result.user.role==='operator'?'dashboard':'entry')};
 const logout=()=>{if(auth?.user?.id){sessionStorage.removeItem('cm-match-'+auth.user.id);sessionStorage.removeItem(`cm-care-start-${auth.user.id}`)}sessionStorage.removeItem('cm-auth');setAuth(null);setMatch(null);setChat(null);setAgreementContext(null);setPage('entry')};
 const completeSurvey=async()=>{setLoading(true);try{const profilePayload={...answers,_meta:{variant:variantContext.id,campusId:variantContext.campusId||null,latitude:variantContext.latitude??null,longitude:variantContext.longitude??null}};await responseJson(await fetch(API+'/api/v1/behavior-profiles/me',{method:'PUT',headers,body:JSON.stringify(profilePayload)}));setAnswers(profilePayload);setProfileComplete(true);const data=await responseJson(await fetch(API+'/api/v1/matches/candidates',{headers,cache:'no-store'}));const recommendation=data.recommended||data.candidates?.[0];if(!recommendation)throw Error('NO_MATCH_CANDIDATE');setMatch({...recommendation,totalCandidates:data.totalCandidates||data.candidates.length});go('match')}catch{alert('현재 버전 조건에 맞는 후보를 찾는 중 문제가 발생했어요. 잠시 후 다시 시도해 주세요.')}finally{setLoading(false)}};
 const startChat=async()=>{if(!match?.candidateId)return;setBusy(true);try{const matchResult=await responseJson(await fetch(API+'/api/v1/matches',{method:'POST',headers,body:JSON.stringify({candidateId:match.candidateId})}));const nextMatch=matchResult.match;const nextStatus=String(nextMatch.status||'').toLowerCase();setMatch(old=>old?{...old,...nextMatch,status:nextStatus,accepted:['accepted','confirmed'].includes(nextStatus),matchId:nextMatch.id}:old);if(nextStatus==='requested'){go('match');return}const hold=await responseJson(await fetch(API+'/api/v1/matches/'+nextMatch.id+'/preauthorize',{method:'POST',headers,body:JSON.stringify({amountKrw:30000})}));const room=await responseJson(await fetch(API+'/api/v1/matches/'+nextMatch.id+'/chat-sessions',{method:'POST',headers,body:JSON.stringify({type:'PRE_MOVE'})}));setChat({...room.chat,matchId:nextMatch.id,paymentId:hold.payment?.id});go('chat')}catch{alert('Chat room could not be prepared. Check the API server.')}finally{setBusy(false)}};
 const openChat=async()=>{if(chat){go('chat');return}if(!match?.matchId)return;setBusy(true);try{const room=await responseJson(await fetch(`${API}/api/v1/matches/${match.matchId}/chat-sessions`,{method:'POST',headers}));setChat({...room.chat,matchId:match.matchId});go('chat')}catch{alert('Chat room could not be opened. Check the API server.')}finally{setBusy(false)}};
 const openMatching=async()=>{if(!auth?.accessToken){go('survey');return}setLoading(true);try{const data=await responseJson(await fetch(API+'/api/v1/matches/candidates',{headers,cache:'no-store'}));const state=data.activeMatch||data.pendingMatch;if(!state){setMatch(null);go('survey');return}const current=data.candidates?.find(c=>state.memberIds.includes(c.candidateId));const status=String(state.status||'').toLowerCase();const nextMatch={...(current||{}),...state,candidateId:current?.candidateId||state.memberIds.find(id=>id!==auth.user.id),matchId:state.id,status,accepted:['accepted','confirmed'].includes(status),totalCandidates:data.totalCandidates||data.candidates?.length||0};setMatch(nextMatch);if(status==='confirmed'){const payment=await responseJson(await fetch(`${API}/api/v1/matches/${state.id}/payment-status`,{headers:{Authorization:'Bearer '+auth.accessToken},cache:'no-store'}));if(payment.allTenantsPaid){const careKey=`cm-care-start-${auth.user.id}`;sessionStorage.setItem(careKey,sessionStorage.getItem(careKey)||payment.payment?.paidAt||new Date().toISOString());go('care')}else{sessionStorage.removeItem(`cm-care-start-${auth.user.id}`);go('confirm')}}else go('match')}catch{go('survey')}finally{setLoading(false)}};
 if(!auth)return <Login onLogin={login} variantContext={variantContext} onChangeVariant={onChangeVariant}/>;
 if(auth.user.role==='operator'||page==='dashboard')return <Dashboard auth={auth} context={context} logout={logout}/>;
 return <div className="app-shell"><header className="topbar"><button className="brand" onClick={()=>go('entry')}><img className="app-logo top-logo" src="/checkmate-logo.svg" alt="CheckMate logo"/><span>CheckMate</span></button></header><main>
  {page==='entry'&&<Entry context={context} consent={consent} setConsent={setConsent} next={()=>go('survey')} profileComplete={profileComplete} openMatching={openMatching} resident={match?.status==='confirmed'} auth={auth} matchId={match?.matchId} candidateId={match?.candidateId}/>}
  {page==='survey'&&<Survey page={questionPage} setPage={setQuestionPage} answers={answers} setAnswers={setAnswers} next={()=>questionPage<2?setQuestionPage(questionPage+1):completeSurvey()} loading={loading}/>}
  {page==='match'&&<Match match={match} back={()=>go('survey')} start={startChat} busy={busy}/>}
  {page==='chatInbox'&&<ChatInbox auth={auth} back={()=>go('entry')} onOpen={(room)=>{setChat(room);setChatType(room.type||'PRE_MOVE');go('chat')}}/>}
  {page==='chat'&&<Chat auth={auth} chat={chat} type={chatType} back={()=>go('chatInbox')} confirm={()=>go('confirm')} onAgreementDraft={(draft)=>{setAgreementContext(draft);go('agreement')}}/>}
  {page==='agreement'&&<AgreementDraftPage auth={auth} draftContext={agreementContext} back={()=>go('chat')}/>}
  {page==='confirm'&&<Confirm roomId={context.roomId} matchId={match?.matchId||chat?.matchId} paymentId={chat?.paymentId} back={()=>go('match')} done={()=>event(context,'contract_confirmed')} care={()=>go('care')}/>}
  {page==='care'&&<CarePage roomId={context.roomId} matchId={match?.matchId||chat?.matchId} auth={auth} back={()=>go('confirm')}/>}
  {page==='calendar'&&<CalendarPage back={()=>go('entry')}/>} 
  {page==='my'&&<MyPage auth={auth} back={()=>go('entry')} logout={logout} onAuthUpdated={setAuth}/>}
 </main><nav className="bottom-nav"><button className={page==='entry'?'active':''} onClick={()=>go('entry')}><Home size={19}/>홈</button><button className={page==='calendar'?'active':''} onClick={()=>go('calendar')}><CalendarDays size={19}/>일정</button><button className={['survey','match','confirm','care'].includes(page)?'active':''} onClick={openMatching}><UsersRound size={19}/>매칭</button><button className={['chat','chatInbox'].includes(page)?'active':''} onClick={()=>go('chatInbox')}><MessageCircle size={19}/>채팅</button><button className={page==='my'?'active':''} onClick={()=>go('my')}><UserRound size={19}/>마이</button></nav></div>
}
